[package]
name = "winregnt"
version = "0.1.1"
authors = ["russ <rustysec@github.com>"]
edition = "2018"

[dependencies]
byteorder = "1"
thiserror = "1"
winapi = { version = "0.3", features = [ "ntdef", "winnt", "ntstatus" ] }
widestring = "0.4"
