[package]
name = "winregnt"
version = "0.1.1"
authors = ["russ <russ@infocyte.com>"]
edition = "2018"

[dependencies]
thiserror = "1"
winapi = { version = "0.3", features = [ "ntdef", "winnt" ] }
widestring = "0.4"
